# Generated by Django 3.2 on 2022-07-06 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_contactno'),
        ('inventory', '0004_inventory_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.organisation'),
        ),
    ]
