# Generated by Django 3.2 on 2022-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_userpermissions_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='CRM_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='Inventory_permission',
            field=models.BooleanField(default=False),
        ),
    ]
