# Generated by Django 3.2 on 2022-07-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_ticket_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='AMC',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
