# Generated by Django 3.2 on 2022-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_ticket_onlineresolvable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TicketID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Ticket ID'),
        ),
    ]
