# Generated by Django 3.2 on 2022-07-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220707_0924'),
        ('crm', '0010_alter_ticket_ticketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='AlternateHW',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory'),
        ),
    ]
