# Generated by Django 3.2 on 2022-07-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_historicalticket_history_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTicket',
        ),
    ]
