# Generated by Django 3.2 on 2022-07-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_historicalticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTicket',
        ),
    ]
