# Generated by Django 3.2 on 2022-07-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20220718_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTicket',
        ),
    ]
